apiVersion: v1
kind: Service
metadata:
  name: oncotarget-lite-api-canary
spec:
  selector:
    app: oncotarget-lite-canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP # Expose the service only within the cluster







